### ISSUE TITLE
Failed to install action OpenAction

### ISSUE THREAD

**Issue by levoncf** [IDArlingTeam/IDArling#100]
when I import and load this project in IDA PRO 7.0, the IDA console shows me this:

```
[ERROR] Failed to initialize
[ERROR] Failed to install action OpenAction
Traceback (most recent call last):
  File "D:/software/ida_prozh/IDA_Pro_v7.0/plugins\idarling\plugin.py", line 140, in init
    self._interface.install()
  File "D:/software/ida_prozh/IDA_Pro_v7.0/plugins\idarling\module.py", line 30, in install
    return self._install()
  File "D:/software/ida_prozh/IDA_Pro_v7.0/plugins\idarling\interface\interface.py", line 91, in _install
    self._open_action.install()
  File "D:/software/ida_prozh/IDA_Pro_v7.0/plugins\idarling\interface\actions.py", line 83, in install
    raise RuntimeError("Failed to install action %s" % action_name)
RuntimeError: Failed to install action OpenAction
```

Any help will be appreciated!

**Comment by patateqbool** [comment]
Hi there,
Can you please provide us a way to reproduce and debug your issue?

Thank you!

**Comment by patateqbool** [comment]
I think I missed you point just before.

I just made a fresh install with IDA Pro 7.0 on a Linux, Mac and Windows, by using the easy install described in the README, it seems to work on my side.
You problem seem to come from this line https://github.com/IDArlingTeam/IDArling/blob/master/idarling/interface/actions.py#L78 returning None/False while trying to instantiate the OpenAction action. Can you please print the value of the arguments passed to this function?

Thank you!
