### ISSUE TITLE
Error when processing non-ascii comments

### ISSUE THREAD

**Issue by NyaMisty** [IDArlingTeam/IDArling#14]
```
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idarling\core\hooks.py", line 495, in _hxe_callback
    self._send_user_cmts(func.startEA)
  File "C:/Program Files/IDA 7.0/plugins\idarling\core\hooks.py", line 538, in _send_user_cmts
    cmts = HexRaysHooks._get_user_cmts(ea)
  File "C:/Program Files/IDA 7.0/plugins\idarling\core\hooks.py", line 532, in _get_user_cmts
    cmts.append(((tl.ea, tl.itp), Event.decode(str(cmt))))
  File "C:/Program Files/IDA 7.0/plugins\idarling\core\events.py", line 70, in decode
    return s.decode(locale.getpreferredencoding())
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 2-3: illegal multibyte sequence
IDAPython: Hex-rays python callback returned non-integer; value ignored.
```
It seems that the IDA uses UTF-8 on windows, too.

**Comment by NeatMonster** [comment]
I've confirmed that Windows also uses UTF-8, I guess [the resource](http://moritzraabe.de/2017/03/28/name-identifiers-and-comment-encoding-in-ida-pro/) I was using wasn't up-to-date.

Thanks @NyaMisty!

**Comment by NyaMisty** [comment]
Haha the IDA loved to change everything :)
