### ISSUE TITLE
Bug in painter when pulling an IDB

### ISSUE THREAD

**Issue by patateqbool** [IDArlingTeam/IDArling#55]
```
[DEBUG] Received packet: Subscribe(name=1769727, color=unnamedd, ea=82181, repo=test2, branch=test2, command_type=subscribe, tick=0, type=command, silent=True)
Traceback (most recent call last):
  File "/home/patate/ida-7.1/plugins/idarling/shared/sockets.py", line 262, in event
    self._dispatch()
  File "/home/patate/ida-7.1/plugins/idarling/shared/sockets.py", line 280, in _dispatch
    elif not self.recv_packet(packet):
  File "/home/patate/ida-7.1/plugins/idarling/network/client.py", line 60, in recv_packet
    self._handlers[packet.__class__](packet)
  File "/home/patate/ida-7.1/plugins/idarling/network/client.py", line 90, in _handle_subscribe
    packet.name, packet.color, packet.ea
  File "/home/patate/ida-7.1/plugins/idarling/interface/painter.py", line 125, in paint
    self.paint_database(name, color, address)
  File "/home/patate/ida-7.1/plugins/idarling/interface/painter.py", line 248, in paint_database
    self.paint_function(name, color, address)
  File "/home/patate/ida-7.1/plugins/idarling/interface/painter.py", line 193, in paint_function
    self._set_paint_function(new_func, color)
  File "/home/patate/ida-7.1/plugins/idarling/interface/painter.py", line 64, in _set_paint_function
    function.color = color
TypeError: in method 'func_t_color_set', argument 2 of type 'bgcolor_t'
```

**Comment by patateqbool** [comment]
Closed by 7f9556cb4a73597201498da2b6ec18883c9d521d
